### ISSUE TITLE
Hookup CMS Editor to Redux / API

### ISSUE THREAD

**Issue by RyanCCollins** [udacityalumni/alumni-client#28]

**Comment by RyanCCollins** [comment]
See here: https://github.com/udacityalumni/alumni-client/tree/feat_rc_article_ui_actions

**Comment by RyanCCollins** [comment]
This is all set, except we could improve the CMS editor by moving the state out into the container and killing the internal state if that's possible.

**Comment by adai183** [comment]
I think the state has to stay inside the CmsEditor component. 
The component is a special case because the editor state is handled by draft.js core.
It is also not needed by by the other components.

The Redux container should only be responsible for calling the api. We can hook up the container to Redux handle all the async logic there and then pass a onSubmit function to the CmsEditor component as a prop.
What do you think ?

**Comment by RyanCCollins** [comment]
Yeah that sounds fine to me!
