### ISSUE TITLE
Content Dashboard

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#65]
Right now we have only an editor. That page should be a fully featured dashboard with the ability to manage existing posts.

**Comment by RyanCCollins** [comment]
Hey @adai183 any updates on this one?  If you need help, let me know.

**Comment by adai183** [comment]
I have to hack megadraft to accept markdown to load content into the editor.
It needs json to load and save article content.
But I thinks we can do a little hack and make it accept markdown. 
I might need some time because I will be at a wedding this weekend. :-)

I made an example using json to load the article content on individual_article_links branch for now.

**Comment by adai183** [comment]
I did some more tests and came to the conclusion that it is fairly complicated to save the editor state as markdown and I think we should instead save it as json. 
So.. question for the backend team: How easy is it to save json in  postgres?
I saw that newer versions of PostgreSQL support the json format but I am not an expert.

**Comment by RyanCCollins** [comment]
So the big missing piece right now on this, is pagination.  This will be challenging, so greatly looking forward to seeing this work!
