### ISSUE TITLE
My Classroom listed twice

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#67]
The 'My Classroom' Menu option is in both menus and active in only one.

**Comment by RyanCCollins** [comment]
Indeed, it is on both on the original mockup.  Do we want it only in one menu?

There are some links there that do not yet link to a page because we have yet to create those pages.  We will have to try to map out what content we want at each place at some point.  For now, maybe I can make a "Not yet ready" page that these all point to.

**Comment by martin-martin** [comment]
Hei - I could make this "Not yet ready" page : ) (= in practice now)
@RyanCCollins if you tell me which paths to direct to there, then I could take this over.

**Comment by forbiddenvoid** [comment]
Shouldn't have been on the mockup. I'd like to leave the one in the right menu.
