### ISSUE TITLE
Expect to have a way to interact with tags and categories as a User and as an Admin

### ISSUE THREAD

**Issue by forbiddenvoid** [udacityalumni/alumni-client#68]
Article Tags should generate an article list with those tags filtered (related to article list not implemented yet)

**Comment by RyanCCollins** [comment]
The way I see it, tags and categorization are the two missing features of our blog.  These tags, in fact, are only statically generate because we don't yet have the required mechanism.  I believe @AbigailMathews is working on this on the backend. 

We do need someone on the front end to be working on this.  Think about how tags and categorization work on a normal blog?  I would expect an input field that has a list of suggested tags.  If the tag is not in the list, the user should be able to add a new one.

We will need a mechanism to essentially manage tags and categories.

**Comment by zhangtreefish** [comment]
I'd like to try this one.

**Comment by RyanCCollins** [comment]
Yeah, I'd love this.  Let's chat about it tomorrow!

**Comment by zhangtreefish** [comment]
Shouldn't tags be an array property of Articles that users can select at CmsEditor along with articleTitle and others:
`constructor(props) {
    super(props);
    // Would be great to move this into redux up to the container.
    this.state = {
      editorState: editorStateFromRaw(null),
      articleTitle: '',
      status: 0,
      spotlighted: false,
    };`
And similarly category also a string property of Article?

**Comment by AbigailMathews** [comment]
The tags branch has not yet been merged with master, but when it is the articles serializer is set to respond with an array of the associated tags. The tags responds with a list of associated articles.

There will need to be some discussion aboit which users can manipulate tags, but I imagine that contributors and admins will have this power.

Another pending feature is that there will separately be a table of nanodegree information, so that an article can be associated with nanodegrees much as it is associated with tags. 

I like the idea of prepopulating the tags, I wonder if the stack overflow categories might be rather extensive for our purposes?

**Comment by zhangtreefish** [comment]
A separate nanodegree table is an awesome feature. Will there be a Udacity projects table? If alumni are interested in sharing, improving, and collaborating on their projects, a project table (or as a sub table of the nanodegree table, if such as possible)  might be relevant.
