### ISSUE TITLE
Individual article links at 'admin/content-dashboard' not routed right

### ISSUE THREAD

**Issue by zhangtreefish** [udacityalumni/alumni-client#87]
To enact the bug: at 'admin/new-story', enter a story and submit.

I expect: the links upon clicking take me to 'articles/:id' page

What happened: Got a 404 land message.

**Comment by RyanCCollins** [comment]
Yes, I have asked @adai183 to work on finishing this.

**Comment by adai183** [comment]
I have to hack megadraft to accept markdown to load content into the editor.
It needs json to load and save article content.
But I thinks we can do a little hack and make it accept markdown. 
I might need some time because I will be at a wedding this weekend. :-)

I made an example using json to load the article content on individual_article_links branch for now.

**Comment by RyanCCollins** [comment]
Awesome!  Thanks for the update.
